name: CI

on:
  push:
    branches:
      - main 
  pull_request:
    branches:
      - main

jobs:
  docker-build-and-push:
    runs-on: ubuntu-latest

    env:
      IMAGE_NAME: ${{ secrets.DOCKERHUB_USERNAME }}/ci-pipeline

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Set Docker image tag
        id: vars
        run: |
          if [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
            echo "tag=latest" >> $GITHUB_OUTPUT
          else
            echo "tag=${{ github.sha }}" >> $GITHUB_OUTPUT
          fi

      - name: Build Docker image
        run: |
          docker build \
            -t $IMAGE_NAME:${{ steps.vars.outputs.tag }} \
            ./frontend

      - name: Push Docker image
        run: |
          docker push $IMAGE_NAME:${{ steps.vars.outputs.tag }}
